### PR TITLE
Multiple mod lists

### LINKED ISSUE #11: Mod-Manager: Allow support for different mod lists files.
Allow support for different mod list files. 
Provide some prebaked ones like RHS.json and CUP.json as well.

Golden case would be the ability to load more than one.

### LINKED ISSUE #12: Mod-Manager: Ability to pull mods.json from github.
Ability to pull mods.json from github. Bake into the ansible perhaps?

### PR DESCRIPTION
**Pull request by Modulator-Mocker-Ellipse8**
Resolves #11 
Resolves #12 

Added:
Can now read any json file named with the -f parameter.
Can now read json from url.
Three new pre-baked mod files. RHS, CUP_Terrains & CUP.
If no login details are provided by param or hardcoded, user will be prompted for them.

@josh-abram can you look over my changes to roles/mod-manager/tasks/main.yml ?
I'm pretty confident that will work, but you know more than me about ansible.

### CODE REVIEW

**Comment by josh-abram** [comment]
Will review tomorrow.

**Comment by Modulator-Mocker-Ellipse8** [comment]
Should prolly test before pulling into master.

**Comment by josh-abram** [comment]
Yeah definitely. Do you have a test environment handy? If not, I can build a Azure server later tonight.

**Comment by Modulator-Mocker-Ellipse8** [comment]
Azure is probably the best bet, make sure you pull this PR and not master for the test though.

**Comment by josh-abram** [comment]
@Eggypapa I have tested this PR from an Ansible perspective but NOT tested the mod manager. We should test it before we merge. I have a test server ready so we can do tomorrow.

**Comment by josh-abram** [comment]
Mod manager tested as well. Working beautifully!

**Review by josh-abram — APPROVED** [review]
Happy with the PR. I've fully tested Ansible/Mod Manager.

**Pull request merged**
